import { Workout } from "@/nextjs/core/models/workout.model";

export const WORKOUTS: Workout[] = [
  {
    id: 1001,
    title: "26 - Jan - Monday",
    iconBgColor: "bg-purple-100",
    warmUp: [
      {
        id: 9001,
        name: "Treadmill Walk",
        equipment: "Machine",
        duration: "5 min",
      },
      {
        id: 9002,
        name: "Leg Swings",
        equipment: "Bodyweight",
        sets: 2,
        reps: 10,
      },
      {
        id: 9003,
        name: "Bodyweight Squat",
        equipment: "Bodyweight",
        sets: 2,
        reps: 15,
      },
    ],
    exercises: [
      {
        id: 1041,
        name: "Smith Machine Squat",
        equipment: "Smith Machine",
        sets: 3,
        reps: 10,
      },
      {
        id: 1312,
        name: "Dumbbell Lunge - Walking",
        equipment: "Dumbbell",
        sets: 4,
        reps: 10,
      },
      {
        id: 1161,
        name: "Smith Machine Romanian Deadlift",
        equipment: "Smith Machine",
        sets: 3,
        reps: 10,
      },
      {
        id: 1164,
        name: "Adductor Machine",
        equipment: "Machine",
        sets: 4,
        reps: 10,
      },
      {
        id: 1084,
        name: "Standing Hip Abduction - Cable",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
      {
        id: 1213,
        name: "Hip Abduction - Cable (Kick-Out)",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
      {
        id: 1294,
        name: "Smith Machine Calf Raise",
        equipment: "Smith Machine",
        sets: 4,
        reps: 20,
      },
    ],
    coolDown: [
      {
        id: 8001,
        name: "Hamstring Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8002,
        name: "Quad Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8003,
        name: "Hip Flexor Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
    ],
  },
  {
    id: 1002,
    title: "26 - Jan - Tuesday",
    iconBgColor: "bg-blue-100",
    warmUp: [
      {
        id: 9004,
        name: "Rowing Machine",
        equipment: "Machine",
        duration: "5 min",
      },
      {
        id: 9005,
        name: "Arm Circles",
        equipment: "Bodyweight",
        sets: 2,
        reps: 15,
      },
      {
        id: 9006,
        name: "Band Pull-Apart",
        equipment: "Resistance Band",
        sets: 2,
        reps: 15,
      },
    ],
    exercises: [
      {
        id: 1425,
        name: "Pulldown - Wide Grip",
        equipment: "Machine",
        sets: 3,
        reps: 10,
      },
      {
        id: 1425,
        name: "Pulldown - Wide Grip",
        equipment: "Machine",
        sets: 3,
        reps: 10,
      },
      {
        id: 1018,
        name: "Seated Cable Row - Neutral Grip",
        equipment: "Cable",
        sets: 3,
        reps: 10,
      },
      {
        id: 1097,
        name: "Chest Supported Row",
        equipment: "Dumbbell",
        sets: 3,
        reps: 10,
      },
      {
        id: 1488,
        name: "Triceps Extension - Cable (One Arm Overhead)",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
      {
        id: 1488,
        name: "Triceps Extension - Cable (One Arm Overhead)",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
      {
        id: 1116,
        name: "Cable Upright Row",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
    ],
    coolDown: [
      {
        id: 8004,
        name: "Lat Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8005,
        name: "Triceps Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8006,
        name: "Shoulder Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
    ],
  },
  {
    id: 1003,
    title: "26 - Jan - Thursday",
    iconBgColor: "bg-indigo-100",
    warmUp: [
      { id: 9007, name: "Elliptical", equipment: "Machine", duration: "5 min" },
      {
        id: 9008,
        name: "Walking Lunges",
        equipment: "Bodyweight",
        sets: 2,
        reps: 10,
      },
      {
        id: 9009,
        name: "Shoulder Dislocations",
        equipment: "Resistance Band",
        sets: 2,
        reps: 12,
      },
    ],
    exercises: [
      {
        id: 1051,
        name: "Barbell Hip Thrust",
        equipment: "Barbell",
        sets: 3,
        reps: 12,
      },
      {
        id: 1042,
        name: "Leg Extension - Single Leg",
        equipment: "Machine",
        sets: 3,
        reps: 10,
      },
      {
        id: 1163,
        name: "Hamstring Curl - Seated",
        equipment: "Machine",
        sets: 3,
        reps: 12,
      },
      {
        id: 1297,
        name: "Smith Machine Shoulder Press",
        equipment: "Smith Machine",
        sets: 4,
        reps: 10,
      },
      {
        id: 1297,
        name: "Smith Machine Shoulder Press",
        equipment: "Smith Machine",
        sets: 4,
        reps: 10,
      },
      {
        id: 1057,
        name: "Cable Face Pull - Rope",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
      {
        id: 1088,
        name: "Dumbbell Lateral Raise - Two Arm",
        equipment: "Dumbbell",
        sets: 4,
        reps: 10,
      },
    ],
    coolDown: [
      {
        id: 8007,
        name: "Glute Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8008,
        name: "IT Band Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8009,
        name: "Rear Delt Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
    ],
  },
  {
    id: 1004,
    title: "26 - Jan - Friday",
    iconBgColor: "bg-pink-100",
    warmUp: [
      {
        id: 9010,
        name: "Jump Rope",
        equipment: "Jump Rope",
        duration: "5 min",
      },
      {
        id: 9011,
        name: "Push-ups",
        equipment: "Bodyweight",
        sets: 2,
        reps: 10,
      },
      {
        id: 9012,
        name: "Arm Swings",
        equipment: "Bodyweight",
        sets: 2,
        reps: 15,
      },
    ],
    exercises: [
      {
        id: 1155,
        name: "Incline Dumbbell Press - Neutral Grip",
        equipment: "Dumbbell",
        sets: 3,
        reps: 10,
      },
      {
        id: 1044,
        name: "Incline Bench Press - Smith Machine",
        equipment: "Smith Machine",
        sets: 3,
        reps: 10,
      },
      {
        id: 1075,
        name: "Dumbbell Incline Fly",
        equipment: "Dumbbell",
        sets: 3,
        reps: 10,
      },
      {
        id: 1370,
        name: "Barbell Curl - Wide Grip",
        equipment: "Barbell",
        sets: 4,
        reps: 10,
      },
      {
        id: 1079,
        name: "Incline Dumbbell Curl",
        equipment: "Dumbbell",
        sets: 4,
        reps: 10,
      },
      {
        id: 1079,
        name: "Incline Dumbbell Curl",
        equipment: "Dumbbell",
        sets: 4,
        reps: 10,
      },
      {
        id: 1389,
        name: "Cable Wrist Curl",
        equipment: "Cable",
        sets: 4,
        reps: 10,
      },
    ],
    coolDown: [
      {
        id: 8010,
        name: "Chest Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8011,
        name: "Biceps Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
      {
        id: 8012,
        name: "Forearm Stretch",
        equipment: "Bodyweight",
        duration: "2 min",
      },
    ],
  },
];
